/**
 * Generates every ArgosFX brand raster into client/public/.
 *
 * Run: npx tsx scripts/brand/generate-brand-assets.ts
 *
 * Why a committed script rather than checked-in binaries alone: the brand accent is not finally
 * settled (amber vs cyan), the wordmark will change if the domain spelling changes, and an OG
 * image regenerated by hand in an image editor drifts from the site it represents. Re-running this
 * is the whole change. The outputs ARE committed too, because the Cloudflare Pages build does not
 * run this - it only copies client/public/.
 *
 * Fonts: generic `sans-serif` / `monospace` families only, deliberately. This matches
 * server/services/signal-chart.ts, which renders correctly on the Linux instance precisely because
 * it never depends on a font being installed. Do not switch these to "Inter" - it resolves on the
 * dev machine and silently falls back in CI.
 *
 * NOTE ON COMPLIANCE: the OG image deliberately carries NO performance figures. CFTC Reg 4.41(b)
 * attaches the prescribed cautionary statement to presentations of hypothetical RESULTS, and a
 * 1200x630 social card cannot carry that statement legibly. Identity and the demo label only.
 * See server/services/telegram-notifier.ts for the full disclosure text and the reasoning.
 */

import { createCanvas, type SKRSContext2D } from '@napi-rs/canvas';
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';

const OUT = path.resolve(import.meta.dirname, '../../client/public');
mkdirSync(OUT, { recursive: true });

/** Brand tokens - keep in sync with client/src/index.css. */
const C = {
  accent: '#F5A524',
  accentInk: '#0E1117',
  bg: '#0E1117',
  surface: '#141922',
  border: '#262E3C',
  text: '#F0F3F7',
  muted: '#94A0B1',
  subtle: '#67717F',
};

/** Rounded rectangle path. `roundRect` exists on this canvas but is spelled defensively here. */
function rr(ctx: SKRSContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

/** The monogram: amber rounded square, dark A. Legible down to 16px. */
function drawMark(ctx: SKRSContext2D, x: number, y: number, size: number) {
  ctx.fillStyle = C.accent;
  rr(ctx, x, y, size, size, size * 0.22);
  ctx.fill();

  ctx.fillStyle = C.accentInk;
  ctx.font = `600 ${Math.round(size * 0.58)}px monospace`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  // Optical centring: the cap-height of "A" sits low against the geometric centre.
  ctx.fillText('A', x + size / 2, y + size / 2 + size * 0.04);
}

function icon(size: number): Buffer {
  const canvas = createCanvas(size, size);
  const ctx = canvas.getContext('2d');
  drawMark(ctx, 0, 0, size);
  return canvas.toBuffer('image/png');
}

/**
 * ICO wrapping a single PNG. Every browser that matters reads PNG-in-ICO, and it avoids
 * hand-rolling a BMP. Header is 6 bytes, one 16-byte directory entry, then the PNG verbatim.
 */
function ico(png: Buffer, size: number): Buffer {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(1, 4); // one image

  const entry = Buffer.alloc(16);
  entry.writeUInt8(size >= 256 ? 0 : size, 0); // width  (0 means 256)
  entry.writeUInt8(size >= 256 ? 0 : size, 1); // height
  entry.writeUInt8(0, 2);  // palette size
  entry.writeUInt8(0, 3);  // reserved
  entry.writeUInt16LE(1, 4);  // colour planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(png.length, 8);
  entry.writeUInt32LE(22, 12); // offset: 6 + 16

  return Buffer.concat([header, entry, png]);
}

/** 1200x630 social card. Identity and the demo label - no performance figures, see header note. */
function ogImage(): Buffer {
  const W = 1200;
  const H = 630;
  const canvas = createCanvas(W, H);
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = C.bg;
  ctx.fillRect(0, 0, W, H);

  // Faint instrument grid - the one piece of ornament, and it earns its place by saying
  // "measurement surface" rather than "marketing banner".
  ctx.strokeStyle = C.border;
  ctx.lineWidth = 1;
  for (let x = 0; x <= W; x += 60) {
    ctx.beginPath(); ctx.moveTo(x + 0.5, 0); ctx.lineTo(x + 0.5, H); ctx.stroke();
  }
  for (let y = 0; y <= H; y += 60) {
    ctx.beginPath(); ctx.moveTo(0, y + 0.5); ctx.lineTo(W, y + 0.5); ctx.stroke();
  }

  // Amber hairline along the top edge - the accent, spent once.
  ctx.fillStyle = C.accent;
  ctx.fillRect(0, 0, W, 4);

  const L = 84;
  drawMark(ctx, L, 96, 76);

  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';

  ctx.fillStyle = C.text;
  ctx.font = '700 88px sans-serif';
  ctx.fillText('ArgosFX', L, 290);

  ctx.fillStyle = C.muted;
  ctx.font = '400 32px sans-serif';
  ctx.fillText('Intraday forex setups, published with the losses attached.', L, 348);

  ctx.fillStyle = C.subtle;
  ctx.font = '400 26px sans-serif';
  ctx.fillText('Pre-registered method. Broker-reconciled fills. Every outcome shown.', L, 394);

  // Demo chip. NFA Interpretive Notice 9025 names the abuse of implying a simulated record
  // is live, so the label travels with the identity, not only with the results.
  const chipY = 470;
  const chipText = 'DEMO — SIMULATED. NO REAL MONEY IS TRADED.';
  ctx.font = '500 22px monospace';
  const chipW = ctx.measureText(chipText).width + 40;

  ctx.fillStyle = C.surface;
  rr(ctx, L, chipY, chipW, 52, 26);
  ctx.fill();
  ctx.strokeStyle = C.border;
  ctx.lineWidth = 1;
  rr(ctx, L + 0.5, chipY + 0.5, chipW - 1, 51, 26);
  ctx.stroke();

  ctx.fillStyle = C.muted;
  ctx.textBaseline = 'middle';
  ctx.fillText(chipText, L + 20, chipY + 27);

  return canvas.toBuffer('image/png');
}

/** Hand-authored so it stays crisp at any size and weighs almost nothing. */
const SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="${C.accent}"/>
  <path d="M32 15.5 46 48.5h-7.4l-2.6-6.4H28l-2.6 6.4H18L32 15.5Zm0 12.9-3.4 8.4h6.8L32 28.4Z" fill="${C.accentInk}"/>
</svg>
`;

const MANIFEST = {
  name: 'ArgosFX',
  short_name: 'ArgosFX',
  description: 'Intraday forex setups, published with the losses attached.',
  start_url: '/',
  display: 'standalone',
  background_color: C.bg,
  theme_color: C.bg,
  icons: [
    { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml' },
  ],
};

const written: Array<[string, number]> = [];
function emit(name: string, data: Buffer | string) {
  const buf = Buffer.isBuffer(data) ? data : Buffer.from(data, 'utf8');
  writeFileSync(path.join(OUT, name), buf);
  written.push([name, buf.length]);
}

emit('favicon.ico', ico(icon(32), 32));
emit('icon.svg', SVG);
emit('apple-touch-icon.png', icon(180));
emit('icon-192.png', icon(192));
emit('icon-512.png', icon(512));
emit('og.png', ogImage());
emit('site.webmanifest', JSON.stringify(MANIFEST, null, 2) + '\n');

console.log(`ArgosFX brand assets -> ${OUT}\n`);
for (const [name, bytes] of written) {
  console.log(`  ${name.padEnd(22)} ${(bytes / 1024).toFixed(1)} KB`);
}
