import { PublicLayout } from "@/components/public-layout";

/**
 * Terms, Privacy and Risk Disclosure.
 *
 * These exist because the login page already told people they had agreed to them:
 * "By continuing, you agree to our Terms of Service and Privacy Policy" was plain
 * text, not links, and neither document existed. Asserting an agreement to documents
 * that are not there is worse than having none.
 *
 * WRITTEN PLAINLY AND HONESTLY, NOT BY A LAWYER. They describe what this service
 * actually does and what it actually stores, which is the part a template would get
 * wrong. They still need review by the commodities attorney already on Philip's
 * compliance checklist before they can be relied on — that review is tracked outside
 * this file, deliberately not advertised on the page itself.
 *
 * CONTACT_EMAIL is null until Philip chooses an address to publish. His personal
 * mailbox is not something to put on a public page without being asked, so the
 * contact line renders only when this is set.
 */
const CONTACT_EMAIL: string | null = null;

const UPDATED = "15 September 2026";

function LegalPage({
  title,
  intro,
  children,
}: {
  title: string;
  intro: string;
  children: React.ReactNode;
}) {
  return (
    <PublicLayout>
      <div className="mx-auto max-w-6xl px-6 py-16">
        <p className="type-label mb-5 text-primary">Last updated {UPDATED}</p>
        <h1 className="type-display measure text-foreground">{title}</h1>
        <p className="measure mt-5 text-lg leading-relaxed text-muted-foreground">{intro}</p>
        <div className="measure mt-12 space-y-10">{children}</div>
        {CONTACT_EMAIL ? (
          <p className="measure mt-12 border-t border-border pt-8 text-sm text-muted-foreground">
            Questions about this document:{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-4">
              {CONTACT_EMAIL}
            </a>
          </p>
        ) : null}
      </div>
    </PublicLayout>
  );
}

function Clause({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="type-h3 text-foreground">{heading}</h2>
      <div className="mt-3 space-y-3 leading-relaxed text-muted-foreground">{children}</div>
    </section>
  );
}

export function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="What ArgosFX is, what it is not, and the terms on which you may use it."
    >
      <Clause heading="What this service is">
        <p>
          ArgosFX publishes trading setups generated by an automated system operating on a{" "}
          <strong className="text-foreground">demo account</strong>. No real money is traded.
          Everything published is general information made available identically to everyone
          who receives it.
        </p>
      </Clause>

      <Clause heading="This is not advice">
        <p>
          Nothing published here is investment, financial, tax or legal advice, and nothing
          is tailored to your circumstances, objectives or risk tolerance. We do not know
          your situation and do not take it into account. You are solely responsible for any
          decision you make.
        </p>
      </Clause>

      <Clause heading="No performance promise">
        <p>
          The system's measured expectancy is negative. We make no claim, promise or
          projection that using anything published here will produce a profit, and any
          statement to the contrary from any source is not authorised by us.
        </p>
      </Clause>

      <Clause heading="Your account">
        <p>
          You are responsible for keeping your login credentials secure and for activity
          under your account. Do not share access. We may suspend or remove an account that
          is being used to abuse the service or to harm others.
        </p>
      </Clause>

      <Clause heading="Availability">
        <p>
          The service is provided as-is and may be unavailable, delayed, incomplete or
          withdrawn at any time without notice. Signals may be late, wrong, or absent
          entirely. Do not build anything on the assumption that it will keep running.
        </p>
      </Clause>

      <Clause heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, we are not liable for any trading loss,
          lost profit, or other loss arising from your use of this service or reliance on
          anything published through it.
        </p>
      </Clause>

      <Clause heading="Changes">
        <p>
          These terms may change. The date at the top of this page reflects the current
          version, and continuing to use the service after a change means accepting it.
        </p>
      </Clause>
    </LegalPage>
  );
}

export function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro="What ArgosFX stores about you, why, and what it never does with it."
    >
      <Clause heading="What we collect">
        <p>
          If you create an account: your <strong className="text-foreground">email address</strong>{" "}
          and a securely hashed password, or — if you sign in with Google — the email address
          and name Google returns. That is the whole of it.
        </p>
        <p>
          We also store the signals you choose to save, so they are there when you come back.
        </p>
      </Clause>

      <Clause heading="What we do not collect">
        <p>
          No payment details, because there is nothing to pay for. No brokerage credentials.
          No trading account access. No advertising or cross-site tracking identifiers.
        </p>
      </Clause>

      <Clause heading="Storage on your device">
        <p>
          Your sign-in token is kept in your browser's local storage so you stay signed in,
          along with small preferences such as which signals you saved. Clearing your browser
          data removes them and signs you out.
        </p>
      </Clause>

      <Clause heading="Who else sees it">
        <p>
          We do not sell your data and we do not share it for marketing. It is held by the
          infrastructure providers that run the service — a database host, an application
          host, and Google if you chose Google sign-in — and used only to operate it.
        </p>
      </Clause>

      <Clause heading="How long we keep it">
        <p>
          For as long as your account exists. Ask us to delete your account and we will
          remove your account record and saved signals.
        </p>
      </Clause>

      <Clause heading="Your choices">
        <p>
          You can ask for a copy of what we hold about you, ask for it to be corrected, or
          ask for it to be deleted.
        </p>
      </Clause>
    </LegalPage>
  );
}

export function Risk() {
  return (
    <LegalPage
      title="Risk Disclosure"
      intro="Read this before you act on anything published here."
    >
      <Clause heading="Trading foreign exchange carries substantial risk">
        <p>
          Trading foreign exchange on margin carries a high level of risk and may not be
          suitable for everyone. Leverage works against you as much as for you. You can lose
          some or all of your capital, and you should not trade money you cannot afford to
          lose. If you are in any doubt, seek advice from an independent, licensed financial
          adviser.
        </p>
      </Clause>

      <Clause heading="Everything published here is simulated">
        <p>
          The system operates on a demo account. It has never traded real money. Results
          shown are hypothetical or simulated.
        </p>
        <p className="rounded-md border-l-2 border-primary bg-primary/[0.06] px-4 py-3">
          Hypothetical or simulated performance results have certain inherent limitations.
          Unlike an actual performance record, simulated results do not represent actual
          trading and may be prepared with the benefit of hindsight. There are frequently
          sharp differences between hypothetical performance results and the actual results
          subsequently achieved by any particular trading programme. No representation is
          being made that any account will or is likely to achieve profits or losses similar
          to those shown.
        </p>
      </Clause>

      <Clause heading="The measured result is negative">
        <p>
          We do not present this system as profitable. Across 1,095 pre-registered trades the
          measured expectancy was −0.0552 R per trade, and measured trading costs exceed the
          strategy's gross edge. We publish that because it is true, not because it helps.
        </p>
      </Clause>

      <Clause heading="Past performance means little">
        <p>
          Past performance, whether actual or simulated, is not indicative of future results.
          Market conditions change, and a result measured over one period says little about
          the next.
        </p>
      </Clause>

      <Clause heading="No advice, no solicitation">
        <p>
          Nothing here is a recommendation or solicitation to buy or sell any instrument, and
          nothing is tailored to you. Information is published identically to everyone who
          receives it.
        </p>
      </Clause>
    </LegalPage>
  );
}
